name: Java CI with Gradle

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
#          cache: gradle # FIXME smth broke with this action and we can't manually delete cache. Turn on in 7 days.
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: gradle build

      - name: Upload build
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build/libs
